x = np.linspace(-4, 4, 400)
F = stats.norm.cdf(x)
ax.plot(x, F, color=ACCENT, lw=2)
ax.axhline(0, color=MUTED, lw=0.8, ls="--")
ax.axhline(1, color=MUTED, lw=0.8, ls="--")
ax.annotate("F(x) -> 0", xy=(-3.9, 0.02), color=INK, fontsize=7.5, va="bottom")
ax.annotate("F(x) -> 1", xy=(1.3, 0.90), color=INK, fontsize=7.5, va="top")
ax.annotate("", xy=(1.4, stats.norm.cdf(1.4)), xytext=(-1.4, stats.norm.cdf(-1.4)),
            arrowprops=dict(arrowstyle="->", color=GOOD, lw=1.6))
ax.text(0.0, 0.60, "always climbing\n(never falls)", color=GOOD, fontsize=8, ha="center")
ax.set_xlabel("x")
ax.set_ylabel("F(x)")
ax.set_ylim(-0.05, 1.08)
ax.set_title("Non-decreasing, 0 to 1: true for any random variable", fontsize=9, loc="left")
