fig = ax.figure
ax.set_position([0.08, 0.18, 0.38, 0.68])
right = fig.add_axes([0.56, 0.18, 0.38, 0.68])
x = np.array([-1, 0, 2])
p = np.array([0.55, 0.15, 0.30])
ax.bar(x, p, color=[BAD, MUTED, GOOD], width=0.6)
ax.set_title("PMF: mass at each point", fontsize=8, loc="left")
ax.set_xlabel("x (R-multiples)")
ax.set_ylabel("p(x)")
right.step(np.r_[-2.5, x, 3.0], np.r_[0, np.cumsum(p), 1.0], where="post", color=ACCENT, lw=2)
right.set_title("CDF: accumulated mass", fontsize=8, loc="left")
right.set_xlabel("x (R-multiples)")
right.set_ylabel("F(x)")
right.set_ylim(0, 1.08)
