n, p = 10, 0.5
mu, var = n*p, n*p*(1-p)
sigma = np.sqrt(var)
r = np.arange(0, n+1)
pmf = stats.binom.pmf(r, n, p)
ax.bar(r, pmf, color=MUTED, width=0.6, zorder=2, label="Binomial PMF")
x = np.linspace(-0.5, n+0.5, 300)
normal_pdf = stats.norm.pdf(x, mu, sigma)
ax.plot(x, normal_pdf, color=ACCENT, lw=2.2, zorder=3, label="Normal(np, np(1-p))")
ax.axvline(mu, color=INK, lw=0.8, ls=(0, (4, 3)))
ax.legend(fontsize=7.5, frameon=False, loc="upper left")
ax.set_xticks(r)
ax.set_xlabel("Years beating the S&P 500 out of 10 (r)")
ax.set_ylabel("Probability / density")
ax.set_title("De Moivre-Laplace: the normal curve already fits at n=10", loc="left")
