m = np.exp(np.cumsum([0, .04, -.07, .03, .02]))
d = np.arange(5)
ax.plot(d, 20 * m, marker='o', color=ACCENT, lw=2, label='20 USD stock (left axis)')
ax.set_ylim(20 * 0.94, 20 * 1.06)
ax.set_ylabel('20 USD stock (USD/share)', color=ACCENT)
ax2 = ax.twinx()
ax2.plot(d, 500 * m, marker='s', ms=9, mfc='none', color=WARM, lw=0, label='500 USD stock (right axis)')
ax2.set_ylim(500 * 0.94, 500 * 1.06)
ax2.set_ylabel('500 USD stock (USD/share)', color=WARM)
ax2.grid(False)
ax.set_xticks(d, ['0', '1', '2', '3', '4'])
ax.set_xlabel('Day')
ax.set_title('Same multipliers: axes 25x apart, points line up', loc='left')
h1, l1 = ax.get_legend_handles_labels()
h2, l2 = ax2.get_legend_handles_labels()
ax.legend(h1 + h2, l1 + l2, loc='lower right', fontsize=8)
