mu=15.;sig=9.;phi=.88;x0=45.;h=np.arange(0,25)
f=mu+phi**h*(x0-mu);sd=sig*np.sqrt((1-phi**(2*h))/(1-phi**2))
ax.fill_between(h,f-1.96*sd,f+1.96*sd,color=WARM,alpha=.25,label='95% band: forecast ± 1.96 SD')
ax.plot(h,f,color=ACCENT,lw=2,label='forecast mean')
ax.axhline(mu,color=GOOD,ls=':',label='long-run mean 15 bp')
ax.errorbar([3],[f[3]],yerr=[[1.96*sd[3]],[1.96*sd[3]]],fmt='o',color=BAD,capsize=4,label='month 3: 35.44, band 8.3 to 62.6')
ax.set_xlabel('horizon (months)');ax.set_ylabel('spread (bp)')
ax.set_title('The forecast returns to 15 bp; the band stops widening at ±37 bp',loc='left');ax.legend(fontsize=7,loc='upper right')
