days = np.array([0, 1, 2, 3])
bal = np.array([12000, 11400, 12150, 11500])
ax.plot(days, bal, marker='o', color=ACCENT, lw=2.2)
ax.axhline(9000, color=BAD, ls=(0,(4,3)), lw=1.2, label='Maintenance margin')
for x, y in zip(days, bal): ax.annotate(f'${y:,.0f}', (x,y), xytext=(0,7), textcoords='offset points', ha='center', fontsize=8)
ax.set_xlabel('Settlement day')
ax.set_ylabel('Margin balance (USD)')
ax.set_title('Daily settlement moves cash before expiry', loc='left')
ax.legend(loc='best')
