days = np.array([-2, -1, 0, 1, 2])
price = np.array([100.4, 100.2, 99.2, 99.4, 99.6])
ax.plot(days, price, marker='o', color=ACCENT, lw=2.1)
ax.axvline(0, color=WARM, ls=(0,(4,3)), lw=1.2, label='Ex-dividend date')
ax.annotate('Dividend $1.00 detached', xy=(0,99.2), xytext=(0.45,100.0), arrowprops=dict(arrowstyle='->', color=WARM), fontsize=8, color=WARM)
ax.set_xlabel('Days around ex-dividend date')
ax.set_ylabel('Stock price (USD)')
ax.set_title('Dividend detachment lowers the theoretical stock price', loc='left')
ax.legend(loc='best')
