p=np.linspace(0,1,101)
expected=(1-p)*100+p*(-600)
ax.plot(p,expected,color=ACCENT,lw=2)
ax.axhline(0,color=MUTED,lw=0.8)
ax.axvline(1/7,color=BAD,ls='--',lw=1,label='break-even p = 1/7')
ax.scatter([0.2],[-40],color=GOOD,zorder=3,label='current p = 0.20')
ax.set_xlabel('event-stress probability, p')
ax.set_ylabel('outer expected P&L (USD/day)')
ax.legend(loc='lower left')
ax.set_title('The Tower output moves with the regime mix',fontsize=9,loc='left')
