# Law of total expectation as areas: bar width = probability of the case, height = mean in that case.
ax.bar(0.40, 100, width=0.80, color=GOOD, alpha=0.8, label='normal day: 80% of days, mean +100')
ax.bar(0.90, -600, width=0.20, color=BAD, alpha=0.8, label='news day: 20% of days, mean -600')
ax.axhline(-40, color=ACCENT, lw=2, ls='--', label='overall mean -40')
ax.axhline(0, color=MUTED, lw=0.8)
ax.text(0.40, 112, 'area +80', ha='center', va='bottom', fontsize=10, weight='bold', color=GOOD)
ax.text(0.90, -612, 'area -120', ha='center', va='top', fontsize=10, weight='bold', color=BAD)
ax.set_xlim(0, 1); ax.set_ylim(-720, 220)
ax.set_xlabel('share of days (probability)')
ax.set_ylabel('USD per day')
ax.legend(fontsize=8, loc='lower left')
ax.set_title('Split by case, then average back: the two areas add to -40', loc='left')
