rng=np.random.default_rng(0)
counts=rng.poisson(12,500)
sums=np.array([rng.normal(75,300,int(n)).sum() if n else 0.0 for n in counts])
ax.scatter(counts,sums,s=10,alpha=0.35,color=ACCENT)
line=np.arange(0,28)
ax.plot(line,75*line,color=BAD,lw=2,label='E[sum | N=n] = 75n')
ax.set_xlabel('fills in day, N')
ax.set_ylabel('realised sum (USD/day)')
ax.legend(loc='upper left')
ax.set_title('Random count drives the centre; increments drive the spread',fontsize=9,loc='left')
