rng=np.random.default_rng(0)
N=rng.poisson(12,4000)
sums=np.array([rng.normal(75,300,int(n)).sum() if n else 0.0 for n in N])
ax.hist(sums,bins=36,color=ACCENT,alpha=0.82,edgecolor='white')
ax.axvline(900,color=BAD,lw=2,ls='--',label='Wald mean = $900/day')
ax.set_xlabel('simulated daily random sum (USD/day)')
ax.set_ylabel('days in simulation')
ax.legend(loc='upper left')
ax.set_title('Random fill count widens the daily P&L distribution',fontsize=9,loc='left')
