fig=ax.figure;fig.delaxes(ax)
a1=fig.add_subplot(2,1,1)
x=np.arange(4)
a1.bar(x-0.19,[1,1,0,0],width=.36,color=MUTED,label='tech loadings, as given')
a1.bar(x+0.19,[.5,.5,-.5,-.5],width=.36,color=ACCENT,label='tech loadings, centred')
a1.axhline(0.5,color=MUTED,ls=':',lw=1.2)
a1.annotate('mean 0.50',xy=(3.4,0.5),xytext=(0,4),textcoords='offset points',fontsize=7,color=MUTED)
a1.axhline(0,color=INK,lw=.9)
a1.set_xticks(x);a1.set_xticklabels(['A','B','C','D'])
a1.set_ylabel('loading');a1.legend(fontsize=6.5,loc='lower left')
a1.set_title('Pull the mean out of one column',loc='left',fontsize=9)
a2=fig.add_subplot(2,1,2)
x2=np.arange(3)
a2.bar(x2-0.19,[0.80,-0.50,0.30],width=.36,color=MUTED,label='factor returns before')
a2.bar(x2+0.19,[0.95,-0.50,0.30],width=.36,color=ACCENT,label='factor returns after')
a2.annotate('the mean has to go somewhere:\nit lands on market',xy=(0.19,0.95),xytext=(0.6,0.72),
            fontsize=7.5,color=ACCENT,arrowprops=dict(arrowstyle='->',color=ACCENT,lw=.8))
a2.axhline(0,color=INK,lw=.9)
a2.set_xticks(x2);a2.set_xticklabels(['market','momentum','tech'])
a2.set_ylabel('factor return today (%)');a2.legend(fontsize=6.5,loc='lower right')
a2.set_title('Asset returns are identical to the last digit',loc='left',fontsize=9)
