x=np.linspace(-1,1,400)
y1=1-np.abs(x)
y2=np.sqrt(np.maximum(0,1-x*x))
ax.plot(x,y1,color=WARM,lw=2,label='L1 = 1')
ax.plot(x,-y1,color=WARM,lw=2)
ax.plot(x,y2,color=ACCENT,lw=2,label='L2 = 1')
ax.plot(x,-y2,color=ACCENT,lw=2)
ax.axhline(0,color=MUTED,lw=.8);ax.axvline(0,color=MUTED,lw=.8)
ax.set_aspect('equal');ax.set_xlim(-1.15,1.15);ax.set_ylim(-1.15,1.15)
ax.set_xlabel('Weight 1');ax.set_ylabel('Weight 2');ax.legend(loc='upper right')
ax.set_title('Different norms impose different portfolio shapes',loc='left')
