ax.plot([-2.4,2.4],[-1.2,1.2],color=BAD,lw=2,label='dependent additions: same line')
ax.fill([-2.0,2.0,2.6,-1.4],[-1.8,0.2,2.2,0.2],color=GOOD,alpha=.18,label='independent pair: area of choices')
ax.quiver(0,0,1.8,.9,angles='xy',scale_units='xy',scale=1,color=ACCENT,width=.009)
ax.quiver(0,0,.6,1.7,angles='xy',scale_units='xy',scale=1,color=WARM,width=.009)
ax.set_xlim(-2.7,2.9); ax.set_ylim(-2.1,2.6)
ax.set_xlabel('Exposure axis 1'); ax.set_ylabel('Exposure axis 2')
ax.legend(loc='upper left',fontsize=7)
ax.set_title('Diversification adds directions, not labels',loc='left')
