ax.axhline(0,color=MUTED,lw=.8); ax.axvline(0,color=MUTED,lw=.8)
ax.quiver(0,0,2.0,0.0,angles='xy',scale_units='xy',scale=1,color=ACCENT,width=.008)
ax.quiver(0,0,0.0,1.7,angles='xy',scale_units='xy',scale=1,color=ACCENT,width=.008)
ax.quiver(0,0,1.4,.9,angles='xy',scale_units='xy',scale=1,color=WARM,width=.008)
ax.quiver(0,0,-.5,1.5,angles='xy',scale_units='xy',scale=1,color=WARM,width=.008)
ax.plot(1.2,1.0,'o',color=GOOD,ms=8)
ax.text(1.3,1.05,'same portfolio',fontsize=8,color=INK)
ax.text(2.05,-.18,'e1',fontsize=8,color=ACCENT); ax.text(-.16,1.78,'e2',fontsize=8,color=ACCENT)
ax.text(1.46,.78,'b1',fontsize=8,color=WARM); ax.text(-.68,1.53,'b2',fontsize=8,color=WARM)
ax.set_aspect('equal');ax.set_xlim(-1,2.7);ax.set_ylim(-.6,2.2)
ax.set_xlabel('Exposure coordinate 1');ax.set_ylabel('Exposure coordinate 2')
ax.set_title('A basis changes the question, not the position',loc='left')
