mu=np.array([0.04,0.03]);S=np.array([[4.0,2.4],[2.4,9.0]])
x=np.linspace(-8,8,200);y=np.linspace(-10,10,220);X,Y=np.meshgrid(x,y)
Z=stats.multivariate_normal(mean=mu,cov=S).pdf(np.dstack((X,Y)))
ax.contour(X,Y,Z,levels=8,colors=ACCENT)
beta=S[0,1]/S[0,0];conditional=mu[1]+beta*(x-mu[0])
xobs=-3.0;yhat=mu[1]+beta*(xobs-mu[0])
ax.plot(x,conditional,color=BAD,lw=2,label='conditional mean, beta = 0.60')
ax.scatter([xobs],[yhat],color=GOOD,s=35,label=f'x=-3.00%, forecast={yhat:.3f}%')
ax.set_xlabel('SPX return (%)');ax.set_ylabel('QQQ return (%)');ax.legend(loc='upper left',fontsize=7)
ax.set_title('Observed SPX return selects a conditional QQQ mean',fontsize=9,loc='left')
